### PR TITLE
draft of this or that

### PR DESCRIPTION
**Pull request by HiranmayaGundu**
Draft of the this or that game

### CODE REVIEW

**Comment by seshrs** [comment]
1) Maybe my laptop screen is small, but here's what it looks like for me:
  image
  Depending on Suhas' laptop, we may want to fix the grid spacing on smaller screens.

2) For the results page, maybe just show the two options and increase the font-weight of the chosen option? (To get rid of the result column.)

3) Ugh the Link on the homepage working 😅

**Comment by HiranmayaGundu** [comment]
@seshrs Could you have a look now? I have added the xs boolean, so they should all be forced to fit in one row now. 

2. Have adopted that, have a look!
3. Oh yeah, sorry forgot to address that. There needs to be an `<a>` tag, it works now!

**Comment by seshrs** [comment]
Looks good! Let's add a link to go back to the home page, maybe as an App Bar.

**Comment by seshrs** [comment]
I'll go ahead and merge.

**Pull request merged**
